pde:
  name: "bilap_high_dim"
  cls: "fracPoisson"
  rhs_type: "one"
  Nobs: 200
  d: 1
  sampling: "grid"
  power: 2.01
  scale: 1000
  init_pad_size: 256
  add_noise: false
  Ntest: 40

kernel:
  type: "fracGaussian"
  anisotropic: false
  sigma_min: 0.001
  sigma_max: 0.3

solver:
  # global defaults shared across phases (unless overridden)
  fp64: true
  alpha: 1.0e-4
  T: 100.0
  gamma: 0.0
  Ntrial: 10000
  blocksize: -1
  print_every: 100
  plot_every: 100

  phases:
    - name: "refine_full"
      solver_name: "full"          # maps to src.solver.solve
      max_step: 3000
      TOL: 1.0e-10
      plot_final: true

  homotopy:
    enabled: false
    num_levels: 2
    alpha_factor: 0.01              # alpha <- alpha * 0.1 after each level
    T_factor: 10                 # T <- T * 10 after each levels